---
version: '3'
services:

  li-pca-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: li-pca-api
    hostname: li-pca-api
    restart: on-failure
    depends_on:
      - li-pca-db
    volumes:
      - .:/usr/src/api
    environment:
      - LI_PCA_DB_USERNAME=lipca
      - LI_PCA_DB_PASSWORD=devpass1
      - LI_PCA_DATABASE=li-pca
    networks:
      - backend
    ports:
      - 8080:8080
      - 8043:443
      - 5678:5678

  li-pca-db:
    container_name: li-pca-db
    hostname: li-pca-db
    restart: always
    image: mongo
    ports:
      - 27017:27017
    # command: --profile=1 --slowms=1
    volumes:
      - "li-pca-db-data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=li-pca
      - MONGO_INITDB_ROOT_PASSWORD=devpass1
      - MONGO_INITDB_DATABASE=li-pca
    networks:
      - backend

  li-pca-web:
    build:
      context: ./src/ui
    container_name: li-pca-web
    hostname: li-pca-web
    restart: on-failure
    depends_on:
      - li-pca-api
    ports:
      - 3000:3000
    volumes:
      - ./src/ui:/usr/src/ui
    command: bash -c "npm ci && npm start --only=prod --no-audit"
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  li-pca-db-data:
