# coding: utf-8
"""Assessment Model"""

from __future__ import absolute_import

# cisagov Libraries
from api import util
from api.models.base_model_ import Model

# from datetime import date, datetime  # noqa: F401
# from typing import Dict, List  # noqa: F401


class Assessment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uuid: str = None):  # noqa: E501
        """Assessment - a model defined in Swagger

        :param uuid: The uuid of this Assessment.  # noqa: E501
        :type uuid: str
        """
        self.swagger_types = {"uuid": str}

        self.attribute_map = {"uuid": "uuid"}
        self._uuid = uuid

    @classmethod
    def from_dict(cls, dikt) -> "Assessment":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Assessment of this Assessment.  # noqa: E501
        :rtype: Assessment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this Assessment.


        :return: The uuid of this Assessment.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this Assessment.


        :param uuid: The uuid of this Assessment.
        :type uuid: str
        """
        if uuid is None:
            raise ValueError(
                "Invalid value for `uuid`, must not be `None`"
            )  # noqa: E501

        self._uuid = uuid
