---
database-name: "li-pca"
database-uri: "mongodb://li-pca:devpass1@li-pca-db:27017/li-pca"
database-user: "li-pca"
connection-max-pool-size: 100
connection-min-pool-size: 0
connection-max-idle-time-ms: 4000
connection-max-concurrent: 2
connection-socket-timeout-ms: 40000
connection-timeout-ms: 40000
connection-wait-queue-timeout-ms: 20000
connection-heartbeat-frequency-ms: 4000
